### ISSUE TITLE
Remove "Deploy to Railway" button

### ISSUE THREAD

**Issue by ghost** [HellBoy-OP/HellBot#46]
This will greatly put your users in danger -  because Railway's Fair Use Policy clearly prohibits deploying userbots. I hope that you can remove that button to prevent Railway from banning user's accounts - this will be more harm than good for your users.

Thank you
Attached the exact content of the Policy, which MUST be followed and accepted before deploying any apps to Railway.
<img width="1280" alt="Screenshot 2021-10-02 at 19 52 20" src="https://user-images.githubusercontent.com/81270448/135738196-b4a2d92a-ba60-48e8-af4f-f5e932063ab6.png">

**Comment by HellBoy-OP** [comment]
Thanks a lot. Totally forgot to remove that button after their changes in fair use policy.
