### ISSUE TITLE
Error While Deploying on VPS

### ISSUE THREAD

**Issue by pakbottest** [HellBoy-OP/HellBot#75]
Hello

Brother i'm getting error Invalid syntax (fonts.py, line 65) wile deploying on VPS.
Pic also attached in this post , Please help me to fix this issue.
![image](https://user-images.githubusercontent.com/116292987/202473493-e3f28fe1-1d2c-4116-88e1-e61f76f74af7.png)

**Comment by ProRaiden** [comment]
> Hello
> 
> Brother i'm getting error Invalid syntax (fonts.py, line 65) wile deploying on VPS. Pic also attached in this post , Please help me to fix this issue. ![image](https://user-images.githubusercontent.com/116292987/202473493-e3f28fe1-1d2c-4116-88e1-e61f76f74af7.png)

Check your python version. It should be `3.10.6` or up.

There are 2 solutions:
1) Update your python version.
`https://cloudbytes.dev/snippets/upgrade-python-to-latest-version-on-ubuntu-linux`

2) Remove that plugin.
`mv TelethonHell/plugins/fonts.py TelethonHell/plugins/fonts`
